In [1]:
!pip install sklearn

pyasn1-modules 0.2.1 has requirement pyasn1<0.5.0,>=0.4.1, but you'll have pyasn1 0.1.9 which is incompatible.
grpcio 1.11.0 has requirement protobuf>=3.5.0.post1, but you'll have protobuf 3.4.1 which is incompatible.


In [18]:
import numpy as np
from sklearn import datasets
import Helpers
from keras.models import Sequential
from keras.layers import Dense

/home/nbuser/anaconda3_420/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [4]:
iris = datasets.load_iris()

In [5]:
features = iris.data
labels = iris.target
flower_names = ["SETOSA", "VERSICOLOR", "VIRGINICA"]

In [6]:
print("total feature records:", len(features))
print("\nFirst five records:\n", features[:5])

total feature records: 150

First five records:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [7]:
features

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
helper = Helpers.Iris

In [11]:
features, labels = helper.shuffle_records(features, labels)

In [12]:
labels

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0,
       1, 2, 0, 1, 2, 0, 2, 2, 1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 0,
       0, 1, 1, 2, 1, 2, 2, 1, 0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1,
       1, 2, 1, 2, 0, 2, 1, 2, 1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2,
       0, 2, 0, 1, 2, 2, 1, 2, 1, 1, 2, 2, 0, 1, 2, 0, 1, 2])

In [13]:
total_classes = 3

In [14]:
one_hot_labels = helper.convert_to_one_hot(labels, total_classes)

In [15]:
print("The original first 5 labels\n",labels[:5])

The original first 5 labels
 [1 0 2 1 1]


In [16]:
print("\nThe first 5 one hot labels\n", one_hot_labels[:5])


The first 5 one hot labels
 [[0 1 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]]


In [17]:
one_hot_labels.shape

(150, 3)

In [19]:
model = Sequential()

In [20]:
model.add(Dense(8, input_dim=4, activation='relu')) # Hidden layer

In [21]:
model

In [22]:
model.add(Dense(3, activation='softmax')) # Judges

In [23]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [24]:
model.get_weights()

[array([[ 0.5410324 ,  0.02581173, -0.25817236,  0.47675484,  0.04592049,
         -0.42498437, -0.10559571,  0.5422986 ],
        [ 0.4273438 ,  0.37697417,  0.45661384, -0.59719926,  0.40006024,
          0.35719472, -0.44658548,  0.4015829 ],
        [ 0.5707826 , -0.68026954,  0.43985277, -0.6002834 ,  0.547882  ,
         -0.6348123 , -0.2870696 , -0.25044566],
        [ 0.40197653,  0.5325455 ,  0.6834578 ,  0.65934366, -0.60527   ,
          0.7055122 ,  0.6598757 , -0.2677387 ]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[ 0.37521285, -0.32287338, -0.34117484],
        [ 0.3985657 ,  0.7227914 , -0.01499951],
        [-0.47350532,  0.516311  ,  0.5440269 ],
        [ 0.51346046, -0.5020323 , -0.2485891 ],
        [ 0.20906305, -0.23769164, -0.6204802 ],
        [-0.2577805 , -0.0747245 , -0.56690246],
        [-0.6387615 ,  0.7205319 , -0.7258959 ],
        [-0.60676306, -0.38143235, -0.5570322 ]], dtype=float32),
 array([0., 0., 0.], dtyp

In [25]:
batch_size = 128

In [26]:
def TrainingLoop(number_of_epochs, verbose):
    model.fit(features, one_hot_labels, \
              batch_size=batch_size, \
              epochs=number_of_epochs, \
              verbose=verbose, \
              validation_split=.1 )

In [27]:
TrainingLoop(1, 1)

Train on 135 samples, validate on 15 samples
Epoch 1/1
135/135 [==============================] - 0s - loss: 2.8466 - acc: 0.3556 - val_loss: 3.7240 - val_acc: 0.1333


In [28]:
TrainingLoop(10, 1)

Train on 135 samples, validate on 15 samples
Epoch 1/10
135/135 [==============================] - 0s - loss: 2.7548 - acc: 0.3556 - val_loss: 3.6024 - val_acc: 0.1333
Epoch 2/10
135/135 [==============================] - 0s - loss: 2.6669 - acc: 0.3556 - val_loss: 3.4807 - val_acc: 0.1333
Epoch 3/10
135/135 [==============================] - 0s - loss: 2.5781 - acc: 0.3556 - val_loss: 3.3596 - val_acc: 0.1333
Epoch 4/10
135/135 [==============================] - 0s - loss: 2.4901 - acc: 0.3556 - val_loss: 3.2395 - val_acc: 0.1333
Epoch 5/10
135/135 [==============================] - 0s - loss: 2.4035 - acc: 0.3556 - val_loss: 3.1214 - val_acc: 0.1333
Epoch 6/10
135/135 [==============================] - 0s - loss: 2.3179 - acc: 0.3556 - val_loss: 3.0051 - val_acc: 0.1333
Epoch 7/10
135/135 [==============================] - 0s - loss: 2.2338 - acc: 0.3556 - val_loss: 2.8897 - val_acc: 0.1333
Epoch 8/10
135/135 [==============================] - 0s - loss: 2.1521 - acc: 0.3556 - val_lo

In [29]:
TrainingLoop(100,0)

In [30]:
TrainingLoop(1,1)

Train on 135 samples, validate on 15 samples
Epoch 1/1
135/135 [==============================] - 0s - loss: 0.6615 - acc: 0.8519 - val_loss: 0.7691 - val_acc: 0.8667


In [31]:
features[69]

array([6.2, 2.9, 4.3, 1.3])

In [32]:
one_hot_labels[69]

array([0, 1, 0])

In [33]:
test_data = np.array([[6.2, 2.9, 4.3, 1.3]])

In [34]:
result = model.predict(test_data, batch_size=1, verbose=1)

1/1 [==============================] - 0s


In [35]:
result

array([[0.2933854 , 0.36991608, 0.3366985 ]], dtype=float32)

In [38]:
flower_names[np.argmax(result, axis=1)[0]]

'VERSICOLOR'

In [40]:
len(features)

150

In [41]:
training_features = features[:135]

In [57]:
test_features = features[135:]

In [58]:
training_one_hot_labels = one_hot_labels[:135]

In [60]:
test_one_hot_labels = one_hot_labels[135:]

In [64]:
split_model = Sequential()

In [65]:
split_model.add(Dense(8, input_dim=4, activation='relu')) # Hidden layer

In [66]:
split_model.add(Dense(3, activation='softmax')) # Judges

In [67]:
split_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [68]:
def SplitTrainingLoop(number_of_epochs, verbose):
    model.fit(training_features, 
              training_one_hot_labels, 
              batch_size=batch_size, 
              epochs=number_of_epochs, 
              verbose=verbose, 
              validation_split=.1, 
              validation_data=(test_features, test_one_hot_labels) )

In [69]:
SplitTrainingLoop(111, 0)

In [70]:
SplitTrainingLoop(1, 1)

Train on 135 samples, validate on 15 samples
Epoch 1/1
135/135 [==============================] - 0s - loss: 0.3720 - acc: 0.9630 - val_loss: 0.4557 - val_acc: 0.9333
