In [1]:
!pip install sklearn

In [2]:
import numpy as np

from sklearn import datasets
iris = datasets.load_iris()

features = iris.data
labels = iris.target

flower_names = ["SETOSA", "VERSICOLOR", "VIRGINICA"]

print("total feature records:", len(features))
print("\nFirst five records:\n", features[:5])

total feature records: 150

First five records:
 [[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]]


In [3]:
print("total labels:", len(labels))
print("\nLabel records:\n", labels)

total labels: 150

Label records:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [4]:
import Helpers

helper = Helpers.Iris


In [5]:

features, labels = helper.shuffle_records(features, labels)

# NOW LET'S LOOK AT THE LABELS AGAIN AND MAKE SURE THEY'RE SHUFFLED
print("total labels:", len(labels))
print("\nLabel records:\n", labels)

total labels: 150

Label records:
 [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0 1 2 2 1 2 1 2 1 0 2 1 0 0 0 1 2 0 0 0 1 0 1 2 0 1 2 0 2 2
 1 1 2 1 0 1 2 0 0 1 1 0 2 0 0 1 1 2 1 2 2 1 0 0 2 2 0 0 0 1 2 0 2 2 0 1 1
 2 1 2 0 2 1 2 1 1 1 0 1 1 0 1 2 2 0 1 2 2 0 2 0 1 2 2 1 2 1 1 2 2 0 1 2 0
 1 2]


In [6]:

total_classes = 3

one_hot_labels = helper.convert_to_one_hot(labels, total_classes)

print("The original first 5 labels\n",labels[:5])
print("\nThe first 5 one hot labels\n", one_hot_labels[:5])

The original first 5 labels
 [1 0 2 1 1]

The first 5 one hot labels
 [[0 1 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]]


In [7]:
one_hot_labels.shape

(150, 3)

In [8]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [9]:

model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    

In [10]:
batch_size = 128

def TrainingLoop(number_of_epochs, verbose):
    model.fit(features, one_hot_labels, \
              batch_size=batch_size, \
              epochs=number_of_epochs, \
              verbose=verbose, \
              validation_split=.1 )
    

In [11]:
TrainingLoop(1, 1)

Train on 135 samples, validate on 15 samples
Epoch 1/1
135/135 [==============================] - 1s 7ms/step - loss: 2.8470 - acc: 0.3556 - val_loss: 3.7485 - val_acc: 0.1333


In [12]:
TrainingLoop(100,0)
TrainingLoop(1, 1)

Train on 135 samples, validate on 15 samples
Epoch 1/1
135/135 [==============================] - 0s 134us/step - loss: 0.7591 - acc: 0.6741 - val_loss: 0.8518 - val_acc: 0.6000


In [13]:
TrainingLoop(100,0)
TrainingLoop(1, 1)

Train on 135 samples, validate on 15 samples
Epoch 1/1
135/135 [==============================] - 0s 126us/step - loss: 0.4702 - acc: 0.8444 - val_loss: 0.5579 - val_acc: 0.8667


In [14]:
TrainingLoop(100,0)
TrainingLoop(1, 1)

Train on 135 samples, validate on 15 samples
Epoch 1/1
135/135 [==============================] - 0s 104us/step - loss: 0.3849 - acc: 0.9259 - val_loss: 0.4642 - val_acc: 0.9333


In [15]:
TrainingLoop(100,0)
TrainingLoop(1, 1)

Train on 135 samples, validate on 15 samples
Epoch 1/1
135/135 [==============================] - 0s 134us/step - loss: 0.3302 - acc: 0.9630 - val_loss: 0.4000 - val_acc: 1.0000


In [16]:
TrainingLoop(100,0)
TrainingLoop(1, 1)

Train on 135 samples, validate on 15 samples
Epoch 1/1
135/135 [==============================] - 0s 108us/step - loss: 0.2898 - acc: 0.9407 - val_loss: 0.3472 - val_acc: 1.0000


In [17]:
TrainingLoop(500,0)
TrainingLoop(1, 1)

Train on 135 samples, validate on 15 samples
Epoch 1/1
135/135 [==============================] - 0s 96us/step - loss: 0.1556 - acc: 0.9778 - val_loss: 0.1552 - val_acc: 1.0000


In [18]:
features[0:3]

array([[ 6.1,  2.8,  4.7,  1.2],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 7.7,  2.6,  6.9,  2.3]])

In [19]:
one_hot_labels[0:3]

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]])

In [20]:
# WE CAN PULL THIS FROM OUR ORIGINAL DATA SET
# THESE FEATURES : [[ 6.1,  2.8,  4.7,  1.2] ] 
# SHOULD RETURN :       1  ( which is VERSICOLOR )
# AS ONE_HOT_ENCODED: [0 1 0]

test_data = np.array( [ [ 6.1,  2.8,  4.7,  1.2] ] )

result = model.predict( test_data, batch_size=1, verbose=1)
result

1/1 [==============================] - 0s 19ms/step


array([[ 0.00394014,  0.74388433,  0.25217557]], dtype=float32)

In [21]:
flower_name_index = np.argmax(result, axis=1)[0]

flower_names[flower_name_index]

'VERSICOLOR'